cd /home/jungao/shared-def-tet/lab-code/human_face_3d/stylegan3_updategit/stylegan3/eg3d-internal-eric-pytorch_antialiasing/eg3d
#python train.py --cfg=shapenet --data=/raid/raid/shapenet_render_res_1024/img/02958343/ --gpus=1 --batch=4 --gamma=3 --outdir=./show_resules/raid/results/shapenet_car_camera_wz_try_with_new_fix_black_back_neural_render_128 --cond=1 --data_camera_mode=shapenet_car --neural_rendering_resolution_final=128 --batch=1 --batch-gpu=1 --mbstd-group=1 --inference 1 --resume ../results/shapenet_car_camera_wz_try_with_new_fix_black_back/00002-shapenet--gpus8-batch32-gamma3/network-snapshot-003600.pkl --inference_show_geo_fid 0 --batch 1 --batch-gpu 1 --mbstd-group 1 --inference_gen_geo 1
#python train.py --cfg=shapenet --data=/raid/raid/shapenet_render_res_1024/img/02958343/ --gpus=1 --batch=4 --gamma=3 --outdir=./show_resules/raid/results/shapenet_car_camera_wz_try_with_new_fix_black_back_neural_render_128 --cond=1 --data_camera_mode=shapenet_car --neural_rendering_resolution_final=128 --batch=1 --batch-gpu=1 --mbstd-group=1 --inference 1 --resume ../results/shapenet_car_camera_wz_try_with_new_fix_black_back/00002-shapenet--gpus8-batch32-gamma3/network-snapshot-003600.pkl --inference_show_geo_fid 1 --batch 1 --batch-gpu 1 --mbstd-group 1
#python train.py --cfg=shapenet --data=/raid/raid/shapenet_render_res_1024/img/03001627/ --gpus=1 --batch=4 --gamma=30 --outdir=./show_resules/raid/results/shapenet_chair_camera_wz_try_with_new_fix_black_back_neural_render_128_try_2 --cond=1 --data_camera_mode=shapenet_chair --neural_rendering_resolution_final=128 --batch=1 --batch-gpu=1 --mbstd-group=1 --inference 1  --resume ../results/shapenet_chair_camera_wz_try_with_new_fix_black_back_neural_render_128_try_2/00001-shapenet--gpus8-batch32-gamma30/network-snapshot-001000.pkl --inference_show_geo_fid 1 --batch 1 --batch-gpu 1 --mbstd-group 1
#python train.py --cfg=shapenet --data=/raid/shapenet_render_res_1024_tmp/img/03790512 --gpus=1 --batch=4 --gamma=3 --outdir=./show_resules/raid/results/shapenet_motorbike_camera_wz_try_with_new_fix_black_back_neural_render_128 --cond=1 --data_camera_mode=shapenet_motorbike --neural_rendering_resolution_final=128 --batch=1 --batch-gpu=1 --mbstd-group=1 --inference 1  --resume ../results/shapenet_motorbike_camera_wz_try_with_new_fix_black_back_neural_render_128/00004-shapenet-03790512-gpus8-batch32-gamma3/network-snapshot-004400.pkl --inference_show_geo_fid 1 --batch 1 --batch-gpu 1 --mbstd-group 1
#python train.py --cfg=shapenet --data=/raid/ts_animal_render_1024/img/Mammal-442 --gpus=1 --batch=4 --gamma=0.3 --outdir=./show_resules/raid/results/ts_animal_camera_wz_try_with_new_fix_black_back_neural_render_128 --cond=1 --data_camera_mode=ts_animal --neural_rendering_resolution_final=128 --batch=1 --batch-gpu=1 --mbstd-group=1 --inference 1  --resume ../results/ts_animal_camera_wz_try_with_new_fix_black_back_neural_render_128/00001-shapenet-Mammal-442-gpus8-batch32-gamma0.3/network-snapshot-002000.pkl --inference_show_geo_fid 1 --batch 1 --batch-gpu 1 --mbstd-group 1
##########################################
##########################################
##########################################
##########################################
##########################################
#python train.py --cfg=shapenet --data=/raid/ts_animal_render_1024/img/Mammal-442 --gpus=1 --batch=4 --gamma=3 --outdir=./show_resules/raid/results/ts_animal_camera_wz_try_with_new_fix_black_back_neural_render_128 --cond=1 --data_camera_mode=ts_animal --neural_rendering_resolution_final=128 --batch=1 --batch-gpu=1 --mbstd-group=1 --inference 1   --resume ../results/ts_animal_camera_wz_try_with_new_fix_black_back_neural_render_128/00004-shapenet-Mammal-442-gpus8-batch32-gamma3/network-snapshot-001400.pkl --inference_show_geo_fid 0 --inference_gen_geo 0
#python train.py --cfg=shapenet --data=/raid/ts_animal_render_1024/img/Mammal-442 --gpus=1 --batch=4 --gamma=3 --outdir=./show_resules/raid/results/ts_animal_camera_wz_try_with_new_fix_black_back_neural_render_128 --cond=1 --data_camera_mode=ts_animal --neural_rendering_resolution_final=128 --batch=1 --batch-gpu=1 --mbstd-group=1 --inference 1   --resume ../results/ts_animal_camera_wz_try_with_new_fix_black_back_neural_render_128/00004-shapenet-Mammal-442-gpus8-batch32-gamma3/network-snapshot-001400.pkl --inference_show_geo_fid 0 --inference_gen_geo 1
python train.py --cfg=shapenet --data=/raid/ts_animal_render_1024/img/Mammal-442 --gpus=1 --batch=4 --gamma=3 --outdir=./show_resules/raid/results/ts_animal_camera_wz_try_with_new_fix_black_back_neural_render_128 --cond=1 --data_camera_mode=ts_animal --neural_rendering_resolution_final=128 --batch=1 --batch-gpu=1 --mbstd-group=1 --inference 1   --resume ../results/ts_animal_camera_wz_try_with_new_fix_black_back_neural_render_128/00004-shapenet-Mammal-442-gpus8-batch32-gamma3/network-snapshot-001400.pkl --inference_show_geo_fid 1 --inference_gen_geo 0

python train.py --cfg=shapenet --data=/raid/raid/shapenet_render_res_1024/img/03001627/ --gpus=1 --batch=4 --gamma=30 --outdir=./show_resules/raid/results/shapenet_chair_camera_wz_try_with_new_fix_black_back_neural_render_128_try_2 --cond=1 --data_camera_mode=shapenet_chair --neural_rendering_resolution_final=128 --batch=1 --batch-gpu=1 --mbstd-group=1 --inference 1  --resume ../results/shapenet_chair_camera_wz_try_with_new_fix_black_back_neural_render_128_try_2/00001-shapenet--gpus8-batch32-gamma30/network-snapshot-001000.pkl --inference_gen_geo 1
python train.py --cfg=shapenet --data=/raid/shapenet_render_res_1024_tmp/img/03790512 --gpus=1 --batch=4 --gamma=3 --outdir=./show_resules/raid/results/shapenet_motorbike_camera_wz_try_with_new_fix_black_back_neural_render_128 --cond=1 --data_camera_mode=shapenet_motorbike --neural_rendering_resolution_final=128 --batch=1 --batch-gpu=1 --mbstd-group=1 --inference 1  --resume ../results/shapenet_motorbike_camera_wz_try_with_new_fix_black_back_neural_render_128/00004-shapenet-03790512-gpus8-batch32-gamma3/network-snapshot-004400.pkl --inference_gen_geo 1
python train.py --cfg=shapenet --data=/raid/ts_animal_render_1024/img/Mammal-442 --gpus=1 --batch=4 --gamma=0.3 --outdir=./show_resules/raid/results/ts_animal_camera_wz_try_with_new_fix_black_back_neural_render_128 --cond=1 --data_camera_mode=ts_animal --neural_rendering_resolution_final=128 --batch=1 --batch-gpu=1 --mbstd-group=1 --inference 1  --resume ../results/ts_animal_camera_wz_try_with_new_fix_black_back_neural_render_128/00001-shapenet-Mammal-442-gpus8-batch32-gamma0.3/network-snapshot-002000.pkl --inference_gen_geo 1

cd /home/jungao/shared-def-tet/lab-code/human_face_3d
python scripts/burn_gpu.py


#python train.py --cfg=shapenet --data=/raid/raid/shapenet_render_res_1024/img/03001627/ --gpus=1 --batch=4 --gamma=30 --outdir=./show_resules/show_pretrained_chair --cond=1 --data_camera_mode=shapenet_chair --neural_rendering_resolution_final=128 --batch=1 --batch-gpu=1 --mbstd-group=1 --inference 1  --resume ../results/shapenet_chair_camera_wz_try_with_new_fix_black_back_neural_render_128_try_2/00001-shapenet--gpus8-batch32-gamma30/network-snapshot-010800.pkl --inference_show_geo_fid 0 --batch 1 --batch-gpu 1 --mbstd-group 1